
* Axiom

- *Axiom 3.1.* (Sets are objects). /IF $A$ is a set, then $A$ is also an object. In particular, given two sets $A$ and $B$, it is meaningful to ask whether $A$ is also an element of $B$./

- *Axiom 3.2.* (Empty set). /There exists a set $\emptyset$, known as the empty set, which contains no elements, i.e., for every object $x$ we have $x\notin\emptyset$./

- *Axiom 3.3.* (Singleton sets and pair sets). /If $a$ is an object, then there exists a set $\{a\}$ whose only element is $a$, i.e., for every object $y$, we have $y\in\{a\}$ if and only if $y=a$; we refer to $\{a\}$ as the *singleton set* whose element is $a$. Furthermore, if $a$ and $b$ are objects, then there exists a set $\{a,b\}$ whose only elements are $a$ and $b$; i.e., for every object $y$, we have $y\in\{a,b\}$ if and only if $y=a$ or $y=b$; we refer to this set as the *pair set* formed by $a$ and $b$./

- *Axiom 3.4.* (Pairwise union). /Given any two sets $A,B$, there exists a set $A\cup B$, called the *union* of $A$ and $B$, which consists of all the elements which belong to $A$ to $B$ or both. In other words, for any object $x$,/
  $$
  x\in A\cup B\iff(x\in A~ or~ x\in B).
  $$

- *Axiom 3.5.* (Axiom of specification). /Let $A$ be a set, and for each $x\in A$, let $P(x)$ be a property pertaining to $x$ (i.e., $P(x)$ is either a true statement or a false statement). Then there exists a set, called $\{x\in A:~P(x)\text{ is true}\}$ (or simply $\{x\in A:~P(x)\})$ for short), whose elements are precisely the elements $x$ in $A$ for which $P(x)$ is true. In other words, for any object $y$,/
  $$
  y\in\{x\in A:~P(x)\text{ is true}\}\iff (y\in A \text{ and } P(y)\text{ is true }).
  $$

- *Axiom 3.6.* (Replacement). /Let $A$ be a set. For any object $x\in A$, and any object $y$, suppose we have a statement $P(x,y)$ pertaining to $x$ and $y$, such that for each $x\in A$ there is at most one $y$ for which $P(x,y)$ is true. Then there exists a set $\{y:~P(x,y)\text{ is true for some } x\in A\}$, such that for any object $z$,/
      $$
      z\in\{y:~P(x,y)\text{ is true for some } x \in A\}\iff P(x,z)\text{ is true for some } x\in A.
      $$

- *Axiom 3.7.* (Infinity). /There exists a set $\mathbb{N}$, whose elements are called natural numbers, as well as an object $0$ in $\mathbb{N}$, and an object $n\pp$ assigned to every natural number $n\in\mathbb{N}$, such that the Peano axioms [[./Chapter2.org][(Axioms 2.1-2.5)]] hold./


* Definitions
- *Definition 3.1.1* (Informal). We define a /set/ $A$ to be any unordered collection of objects, e.g., $\{3,8,5,2\}$ is a set. If $x$ is an object, we say that $x$ /is an element of/ $A$ or $x\in A$ if $x$ lies in the collection; otherwise we say that $x\notin A$. For instance, $3\in\{1,2,3,4,5\}$ but $7\notin\{1,2,3,4,5\}$.
    :PROPERTIES:
  :CUSTOM_ID: definition-3.1.1
  :END:

- *Definition 3.1.4.* (Equality of sets). /Two sets $A$ and $B$ are equal, $A=B$ iff every element of $A$ is an element of $B$ and vice versa. To put it another way, $A=B$ if and only if every element $x$ of $A$ belongs also to $B$, and every element $y$ of $B$ belongs also to $A$./

- *Definition 3.1.15* (Subsets). Let $A,B$ be sets. We say that $A$ is a /subset/ of $B$, denoted $A\subseteq B$, iff every every element of $A$ is also an element of $B$, i.e.
      $$
      \text{For any object }x,~~x\in A\implies x\in B.
      $$
      We say that $A$ is a proper subset of $B$, denoted $A\subsetneq B$, if $A\subseteq B$ and $A\neq B$.
    :PROPERTIES:
  :CUSTOM_ID: definition-3.1.14
  :END:

- *Definition 3.1.23* (Intersections). The /intersection/ $S_1\cap S_2$ of two sets is defined to be the set
      $$
      S_1\cap S_2:=\{s\in S_1:x\in S_2\}.
      $$
      In other words, $S_1\cap S_2$ consists of all the elements which belong to both $S_1$ and $S_2$. Thus, for all objects $x$,
      $$
      x\in S_1\cap S_2\iff x\in S_1\text{ and }x\in S_2.
      $$
    :PROPERTIES:
  :CUSTOM_ID: definition-3.1.22
  :END:

- *Definition 3.1.27* (Difference sets). Given two sets $A$ and $B$, we define the set $A-B$ or $A\setminus B$ to be the set $A$ with any elements of $B$ removed:
      $$
      A\setminus B:=\{x\in A:x\notin B\};
      $$
      for instance, $\{1,2,3,4\}\setminus\{2,4,6\}=\{1,3\}$. In many cases $B$ will be a subset of $A$, but not necessarily.
    :PROPERTIES:
  :CUSTOM_ID: definition-3.1.26
  :END:


* Propositions

- *Lemma 3.1.6.* (Single choice). /Let $A$ be a non-empty set. Then there exists an objet $x$ such that $x\in A$./
  :PROPERTIES:
  :CUSTOM_ID: lemma-3.1.5
  :END:

  - [[./Chapter3/lemma-3.1.6.org][Proof by Tao]]

- *Lemma 3.1.13* /If $a$ and $b$ are objects, then $\{a,b\}=\{a\}\cup\{b\}$. If $A,B,C$ are sets, then the union operation is commutative (i.e., $A\cup B= B\cup A$) and associative (i.e., $(A\cup B)\cup C=A\cup(B\cup C))$. Also, we have $A\cup A=A\cup\emptyset=\emptyset\cup A=A$./
  :PROPERTIES:
  :CUSTOM_ID: lemma-3.1.12
  :END:

  - [[./Chapter3/lemma-3.1.13.org][Proof by Tao]]
  - $Proof$. See [[./Chapter3/Exercises/exercise-3.1.3.org][Exercise 3.1.3]]

* Exercises
 - *Exercise 3.1.2* /Using only [[./Chapter3/definition-3.1.4.org][Definition 3.1.4]], [[./Chapter3/axiom-3.1.org][Axiom 3.1]], [[./Chapter3/axiom-3.2.org][Axiom 3.2]], and [[./Chapter3/axiom-3.3.org][Axiom 3.3]], prove that the sets $\emptyset, \{\emptyset\}, \{\{\emptyset\}\}$, and $\{\emptyset, \{\emptyset\}\}$ are all distinct (i.e, no two of them are equal to each other)./
 - [[./Chapter3/Exercises/exercise-3.1.2.org][Exercise-3.1.2 with solution]]

 - *Exercise 3.1.3.* Prove [[./Chapter3/lemma-3.1.13.org][Lemma 3.1.13]]
  :PROPERTIES:
  :CUSTOM_ID: excercise-3.1.3
  :END:

   [[./Chapter3/Exercises/exercise-3.1.3.org][Exercise-3.1.3 with solution]]
